'use client';
import { createContext, useContext, useState, useEffect } from 'react';

export const LangContext = createContext({ lang: 'uz', setLang: () => { } });

export function LangProvider({ children }) {
  const [lang, setLangState] = useState('uz');
  useEffect(() => {
    const s = localStorage.getItem('lang');
    if (s === 'uz_cryl') setLangState('uz_cryl');
  }, []);
  function setLang(l) { localStorage.setItem('lang', l); setLangState(l); }
  return <LangContext.Provider value={{ lang, setLang }}>{children}</LangContext.Provider>;
}

export function useLang() { return useContext(LangContext); }

export const T = {
  uz: {
    // Nav
    topics: 'Mavzular', tickets: 'Biletlar', exam: 'Imtihon', videos: 'Video darslar',
    saved: ' Saqlangan', battle: ' 1vs1', marathon: ' Marafon',
    login: 'Kirish', logout: 'Chiqish', admin: 'Admin',
    // Common
    loading: 'Yuklanmoqda...', next_q: 'Keyingi savol', see_result: "Natijani ko'rish",
    correct: "To'g'ri javob!", wrong: "Noto'g'ri", restart: 'Qayta urinish',
    correct_l: "To'g'ri", wrong_l: "Noto'g'ri", total_l: 'Jami', cancel: 'Bekor qilish',
    // Login
    login_tab: 'Kirish', reg_tab: "Ro'yxatdan o'tish",
    name_l: 'Ism', password_l: 'Parol', admin_setup: 'Admin sozlash',
    kicked: 'Hisobingizga boshqa qurilmadan kirildi. Iltimos, qayta kiring.',
    pending_done: "Ro'yxatdan o'tdingiz!", pending_msg: "Hisobingiz admin tomonidan tasdiqlanishi kerak. Tasdiqlangandan so'ng tizimga kirishingiz mumkin.",
    go_login: "Kirishga o'tish",
    // Mavzular
    topics_title: "Mavzular bo'yicha test", topics_sub: "Har bir mavzuni alohida o'rganing",
    topics_total: 'Jami mavzular', topics_done: 'Yakunlangan', topics_qs: 'Jami savollar',
    search_ph: 'Mavzu nomini qidiring...',
    not_done: "Hali o'tilmagan", btn_restart: 'Qayta', btn_continue: 'Davom', btn_start: 'Boshlash',
    q_count: 'ta savol',
    // Topic test
    back_topics: "Mavzularga qaytish", congrats: 'Tabriklaymiz!', study_more: "Yana o'qing",
    // Biletlar
    tickets_title: 'Biletlar', tickets_sub: 'Har bir biletda 20 ta savol — rasmiy imtihon shakli',
    coming_soon: 'Tez orada', coming_soon_sub: 'Bu bilet hozircha tayyorlanmoqda. Tez orada ochiladi!',
    ticket_l: 'Bilet', done_l: 'Bajarildi', back_tickets: 'Biletlarga qaytish',
    tickets_total: 'Jami biletlar', tickets_done_pct: 'Yakunlangan (80%+)', q_per_ticket: 'Savol soni',
    results_l: 'Natijalar',
    // Imtihon
    exam_title: 'Imtihon rejimi', exam_sub: "Tasodifiy savollar bilan o'zingizni sinab ko'ring",
    exam_prep: 'Savollar tayyorlanmoqda...', exam_great: 'Ajoyib natija!',
    exam_more: "Ko'proq mashq qiling", exam_restart: 'Qayta boshlash', finish: 'Yakunlash',
    timer_warn: 'Vaqt tugaganda imtihon avtomatik yakunlanadi',
    answered: 'javob berildi', unanswered: 'Javobsiz', min_l: 'daqiqa', pass_l: "O'tish: 80%",
    // Saved
    saved_title: '🔖 Saqlangan savollar', saved_qs: 'ta savol saqlangan',
    saved_empty_t: 'Hech narsa saqlanmagan',
    saved_empty_s: "Test yechayotganda 🔖 belgisini bosib savollarni saqlang",
    go_topics: "Mavzularga o'tish", start_test: '▶ Test boshlash', back_list: "Ro'yxatga qaytish",
    // Notes
    note_l: 'Izoh', note_add: "Izoh qo'shish", note_edit: "Izohni tahrirlash",
    note_save: 'Saqlash', note_del: "O'chirish", note_saving: 'Saqlanmoqda...',
    note_ph: "Bu savol bo'yicha izoh yozing...", note_del_confirm: "Izohni o'chirasizmi?",
    // Battle
    battle_title: '⚔️ 1 vs 1 Raqobat', battle_sub: "Do'stingiz bilan yoki random raqib bilan kurashing",
    friend_mode: 'Sherik bilan', friend_desc: "Havolani do'stingizga yuboring",
    random_mode: 'Random', random_desc: 'Tasodifiy raqib bilan',
    share_title: 'Havolani yuboring', share_sub: "Do'stingiz havolani ochsa, o'yin boshlanadi",
    copy_l: 'Nusxalash', copied_l: '✓ Nusxalandi', go_game: "O'yinga kirish →",
    searching: 'Raqobatchi axtarilmoqda...', searching_sub: "30 soniya ichida topilmasa bekor bo'ladi",
    not_found: 'Raqobatchi topilmadi', not_found_s: "Hozir boshqa foydalanuvchi yo'q. Keyinroq urinib ko'ring.",
    retry_l: 'Qayta urinish', top_players: "Eng yaxshi o'yinchilar", no_games: "Hali o'yinlar bo'lmagan",
    pts_l: 'ochko', waiting_friend: "Do'stingizni kutmoqda...",
    waiting_sub: "Havolani do'stingizga yuboring. U kirgach o'yin boshlanadi.",
    copy_short: 'Nusxa', opp_wait: 'Raqib kutilmoqda...',
    you_won: 'Siz yutdingiz!', you_lost: 'Siz yutqazdingiz',
    pts_plus: "+5 ochko qo'shildi", pts_minus: '−5 ochko ayirildi',
    you_l: '👤 Siz', opp_l: '👤 Raqib', home_l: 'Bosh sahifa',
    rematch: "Qayta o'ynash", tie_note: '* Teng natija — tezroq tugallagan yutdi',
    joining: "O'yinga qo'shilmoqda...", room_404: 'Xona topilmadi',
    room_full: "Bu xona to'la yoki mavjud emas", back_battle: 'Raqobatga qaytish',
    wait_done: 'Raqib tugashini kutmoqda...', q_l: 'Savol',
    player_count: "Nechta kishi o'ynaydi?", create_room: 'Xona yaratish',
    waiting_room: 'Kutish xonasi', slot_empty: "Bo'sh o'rin",
    start_game: "O'yinni boshlash", need_more: "Kamida 2 ta o'yinchi kerak",
    room_code_l: 'Xona kodi', final_result: 'Yakuniy natijalar',
    rank_l: "O'rin", players_l: "O'yinchilar", live_score: 'Jonli reyting',
    q_source: 'Savollar manbai', src_random: 'Random 20 ta', src_topic: 'Mavzu bo\'yicha', src_ticket: 'Bilet bo\'yicha',
    pick_topic: 'Mavzu tanlang', pick_ticket: 'Bilet tanlang', q_count_l: 'ta savol',
    // Modules
    videos_title: 'Video darsliklar',
    videos_sub_admin: "Modullarni boshqaring va darslar qo'shing",
    videos_sub_user: "Modulni tanlang va o'rganishni boshlang",
    no_modules: "Hozircha modul yo'q",
    lessons_l: 'Darslar', add_lesson: '+ Dars qo\'sh', no_lessons: "Hali dars qo'shilmagan",
    completed_pct: 'yakunlangan', lessons_count: 'dars',
    btn_review: "Qayta ko'rish", btn_cont: 'Davom etish',
    // Marathon
    mar_title: 'Marafon rejimi', mar_sub: "Har bir to'g'ri javob uchun +1 savol qo'shiladi!",
    mar_rules_t: 'Qoidalar',
    mar_rule1: "To'g'ri javob → +1 ta yangi savol qo'shiladi",
    mar_rule2: "Noto'g'ri javob → hech narsa qo'shilmaydi",
    mar_rule3: "3 ta savol bilan boshlanadi — imkon qadar uzaytiring!",
    mar_added: "yangi savol qo'shildi", mar_queue: 'Navbatda',
    mar_done_t: 'Marafon tugadi!', mar_record: 'Rekord',
    mar_new_rec: 'Yangi rekord!', mar_total_desc: "to'g'ri javob berdingiz",
    mar_start: 'Marafon boshlash',
    // Home
    home_badge: "Haydovchilik guvohnomasi",
    home_title: "Haydovchilik guvohnomasi imtihoniga Avtoqoida bilan tayyorlaning",
    home_desc: "Biletlar, mavzular bo'yicha testlar, video darslar va imtihon rejimi — hammasi bir joyda.",
    home_start_tickets: "Biletlarni boshlash", home_start_exam: "Imtihon rejimi",
    home_free_start: "Bepul boshlash", home_view_topics: "Mavzularni ko'rish",
    home_sections: "Barcha o'quv bo'limlari", home_choose: "O'zingizga qulay usulni tanlang",
    home_begin: "Boshlash →",
    home_cta_t: "Hoziroq boshlang",
    home_cta_s: "Bepul ro'yxatdan o'ting va barcha materiallarga kiring",
    home_cta_btn: "Ro'yxatdan o'tish",
    home_welcome: "Salom,", home_continue: "qayerdan davom etasiz?",
    stat_qs: "Savollar", stat_tickets_l: "Biletlar", stat_topics_l: "Mavzular", stat_videos_l: "Video darslar",
    feat_topics_t: "Mavzular bo'yicha test", feat_topics_d: "Har bir mavzuni alohida o'rganing. 30+ mavzu va 1220 ta savol.",
    feat_tickets_t: "Biletlar", feat_tickets_d: "Rasmiy imtihon biletlari — 61 ta bilet, har birida 20 ta savol.",
    feat_exam_t: "Imtihon rejimi", feat_exam_d: "Tasodifiy 50 yoki 100 ta savol. Vaqt chegarasi bilan o'zingizni sinang.",
    feat_videos_t: "Video darslar", feat_videos_d: "Haydovchilik qoidalarini video orqali o'rganing. Modullar bo'yicha.",
    feat_battle_t: "1vs1 Raqobat", feat_battle_d: "Do'stingiz yoki tasodifiy raqib bilan bellashing. Kim tezroq va to'g'riroq?",
    feat_marathon_t: "Marafon rejimi", feat_marathon_d: "Har bir to'g'ri javob uchun +1 savol. Imkon qadar uzoqroq chida!",
    feat_hard_t: "Murakkab savollar", feat_hard_d: "Eng qiyin savollar to'plami. Tayyorgarligingizni sinab ko'ring.",
    feat_num_t: "Raqamli savollar", feat_num_d: "Raqamlar va me'yorlar bo'yicha maxsus savollar.",
    feat_50_t: "50 ta savol", feat_50_d: "Tezkor mashq — 50 ta tasodifiy savol, 50 daqiqa vaqt.",
    feat_100_t: "100 ta savol", feat_100_d: "Keng qamrovli mashq — 100 ta tasodifiy savol, 100 daqiqa vaqt.",
    // Imtihon simulation
    sim_title: "Imtihon simulatsiyasi", sim_sub: "20 ta savol · 3 xato = yiqilish · 20 daqiqa",
    sim_rules_t: "Imtihon qoidalari",
    sim_rule1: "20 ta tasodifiy savol beriladi",
    sim_rule2: "3 ta xato qilsangiz imtihon darhol tugaydi",
    sim_rule3: "20 daqiqa vaqt beriladi",
    sim_rule4: "18 ta to'g'ri javob (85%) — o'tish chegarasi",
    sim_errors: "Xatolar", sim_start: "Imtihonni boshlash",
    sim_fail_t: "Imtihondan yiqildingiz!", sim_fail_s: "3 ta xato qildingiz.",
    sim_time_up: "Vaqt tugadi!", sim_pass_t: "Tabriklaymiz, o'tdingiz!",
    sim_pass_s: "Imtihondan muvaffaqiyatli o'tdingiz.",
    sim_not_pass: "O'ta olmadingiz", sim_errors_made: "ta xato",
    // Mashq
    mashq_title: "Mashq rejimi",
    // Xatolar
    xato_title: "Xatolar", xato_sub: "Oxirgi 20 ta xato qilgan savollar",
    feat_xato_t: "Xatolar bo'limi", feat_xato_d: "Oxirgi 20 ta xato qilgan savollaringiz bilan mashq qiling.",
    xato_empty: "Hali xato qilmagansiz!", xato_empty_sub: "Mavzular yoki imtihon ishlang — xatolar bu yerda paydo bo'ladi.",
    q_count: "ta savol",
  },
  uz_cryl: {
    // Nav
    topics: 'Мавзулар', tickets: 'Билетлар', exam: 'Имтиҳон', videos: 'Видео дарслар',
    saved: '🔖 Сақланган', battle: '⚔️ 1vs1', marathon: '🏃 Марафон',
    login: 'Кириш', logout: 'Чиқиш', admin: 'Админ',
    // Common
    loading: 'Юкланмоқда...', next_q: 'Кейинги савол', see_result: 'Натижани кўриш',
    correct: 'Тўғри жавоб!', wrong: 'Нотўғри', restart: 'Қайта уриниш',
    correct_l: 'Тўғри', wrong_l: 'Нотўғри', total_l: 'Жами', cancel: 'Бекор қилиш',
    // Login
    login_tab: 'Кириш', reg_tab: 'Рўйхатдан ўтиш',
    name_l: 'Исм', password_l: 'Парол', admin_setup: 'Админ созлаш',
    kicked: 'Ҳисобингизга бошқа қурилмадан кирилди. Илтимос, қайта киринг.',
    pending_done: 'Рўйхатдан ўтдингиз!', pending_msg: 'Ҳисобингиз админ томонидан тасдиқланиши керак. Тасдиқлангандан сўнг тизимга киришингиз мумкин.',
    go_login: 'Киришга ўтиш',
    // Mavzular
    topics_title: 'Мавзулар бўйича тест', topics_sub: 'Ҳар бир мавзуни алоҳида ўрганинг',
    topics_total: 'Жами мавзулар', topics_done: 'Якунланган', topics_qs: 'Жами саволлар',
    search_ph: 'Мавзу номини қидиринг...',
    not_done: 'Ҳали ўтилмаган', btn_restart: 'Қайта', btn_continue: 'Давом', btn_start: 'Бошлаш',
    q_count: 'та савол',
    // Topic test
    back_topics: 'Мавзуларга қайтиш', congrats: 'Табриклаймиз!', study_more: 'Яна ўқинг',
    // Biletlar
    tickets_title: 'Билетлар', tickets_sub: 'Ҳар бир билетда 20 та савол — расмий имтиҳон шакли',
    coming_soon: 'Тез орада', coming_soon_sub: 'Бу билет ҳозирча тайёрланмоқда. Тез орада очилади!',
    ticket_l: 'Билет', done_l: 'Бажарилди', back_tickets: 'Билетларга қайтиш',
    tickets_total: 'Жами билетлар', tickets_done_pct: 'Якунланган (80%+)', q_per_ticket: 'Савол сони',
    results_l: 'Натижалар',
    // Imtihon
    exam_title: 'Имтиҳон режими', exam_sub: 'Тасодифий саволлар билан ўзингизни синаб кўринг',
    exam_prep: 'Саволлар тайёрланмоқда...', exam_great: 'Ажойиб натижа!',
    exam_more: 'Кўпроқ машқ қилинг', exam_restart: 'Қайта бошлаш', finish: 'Якунлаш',
    timer_warn: 'Вақт тугаганда имтиҳон автоматик якунланади',
    answered: 'жавоб берилди', unanswered: 'Жавобсиз', min_l: 'дақиқа', pass_l: 'Ўтиш: 80%',
    // Saved
    saved_title: '🔖 Сақланган саволлар', saved_qs: 'та савол сақланган',
    saved_empty_t: 'Ҳеч нарса сақланмаган',
    saved_empty_s: 'Тест ечаётганда 🔖 белгисини босиб саволларни сақланг',
    go_topics: 'Мавзуларга ўтиш', start_test: '▶ Тест бошлаш', back_list: 'Рўйхатга қайтиш',
    // Notes
    note_l: 'Изоҳ', note_add: 'Изоҳ қўшиш', note_edit: 'Изоҳни таҳрирлаш',
    note_save: 'Сақлаш', note_del: 'Ўчириш', note_saving: 'Сақланмоқда...',
    note_ph: 'Бу савол бўйича изоҳ ёзинг...', note_del_confirm: 'Изоҳни ўчирасизми?',
    // Battle
    battle_title: '⚔️ 1 vs 1 Рақобат', battle_sub: 'Дўстингиз билан ёки рандом рақиб билан курашинг',
    friend_mode: 'Шерик билан', friend_desc: 'Ҳаволани дўстингизга юборинг',
    random_mode: 'Рандом', random_desc: 'Тасодифий рақиб билан',
    share_title: 'Ҳаволани юборинг', share_sub: 'Дўстингиз ҳаволани очса, ўйин бошланади',
    copy_l: 'Нусхалаш', copied_l: '✓ Нусхаланди', go_game: 'Ўйинга кириш →',
    searching: 'Рақобатчи ахтарилмоқда...', searching_sub: '30 сония ичида топилмаса бекор бўлади',
    not_found: 'Рақобатчи топилмади', not_found_s: 'Ҳозир бошқа фойдаланувчи йўқ. Кейинроқ уриниб кўринг.',
    retry_l: 'Қайта уриниш', top_players: 'Энг яхши ўйинчилар', no_games: 'Ҳали ўйинлар бўлмаган',
    pts_l: 'очко', waiting_friend: 'Дўстингизни кутмоқда...',
    waiting_sub: 'Ҳаволани дўстингизга юборинг. У кирганда ўйин бошланади.',
    copy_short: 'Нусха', opp_wait: 'Рақиб кутилмоқда...',
    you_won: 'Сиз ютдингиз!', you_lost: 'Сиз ютқаздингиз',
    pts_plus: '+5 очко қўшилди', pts_minus: '−5 очко айирилди',
    you_l: '👤 Сиз', opp_l: '👤 Рақиб', home_l: 'Бош саҳифа',
    rematch: 'Қайта ўйнаш', tie_note: '* Тенг натижа — тезроқ тугаллаган ютди',
    joining: 'Ўйинга қўшилмоқда...', room_404: 'Хона топилмади',
    room_full: 'Бу хона тўла ёки мавжуд эмас', back_battle: 'Рақобатга қайтиш',
    wait_done: 'Рақиб тугашини кутмоқда...', q_l: 'Савол',
    player_count: 'Нечта киши ўйнайди?', create_room: 'Хона яратиш',
    waiting_room: 'Кутиш хонаси', slot_empty: 'Бўш ўрин',
    start_game: 'Ўйинни бошлаш', need_more: 'Камида 2 та ўйинчи керак',
    room_code_l: 'Хона коди', final_result: 'Якуний натижалар',
    rank_l: 'Ўрин', players_l: 'Ўйинчилар', live_score: 'Жонли рейтинг',
    q_source: 'Саволлар манбаи', src_random: 'Рандом 20 та', src_topic: 'Мавзу бўйича', src_ticket: 'Билет бўйича',
    pick_topic: 'Мавзу танланг', pick_ticket: 'Билет танланг', q_count_l: 'та савол',
    // Modules
    videos_title: 'Видео дарсликлар',
    videos_sub_admin: 'Модулларни бошқаринг ва дарслар қўшинг',
    videos_sub_user: 'Модулни танланг ва ўрганишни бошланг',
    no_modules: 'Ҳозирча модул йўқ',
    lessons_l: 'Дарслар', add_lesson: '+ Дарс қўш', no_lessons: 'Ҳали дарс қўшилмаган',
    completed_pct: 'якунланган', lessons_count: 'дарс',
    btn_review: 'Қайта кўриш', btn_cont: 'Давом этиш',
    // Marathon
    mar_title: 'Марафон режими', mar_sub: 'Ҳар бир тўғри жавоб учун +1 савол қўшилади!',
    mar_rules_t: 'Қоидалар',
    mar_rule1: 'Тўғри жавоб → +1 та янги савол қўшилади',
    mar_rule2: 'Нотўғри жавоб → ҳеч нарса қўшилмайди',
    mar_rule3: '3 та савол билан бошланади — имкон қадар узайтиринг!',
    mar_added: 'янги савол қўшилди', mar_queue: 'Навбатда',
    mar_done_t: 'Марафон тугади!', mar_record: 'Рекорд',
    mar_new_rec: 'Янги рекорд!', mar_total_desc: 'тўғри жавоб бердингиз',
    mar_start: 'Марафон бошлаш',
    // Home
    home_badge: "Ҳайдовчилик гувоҳномаси",
    home_title: "Автоқоида имтиҳонига ишонч билан тайёрланинг",
    home_desc: "Билетлар, мавзулар бўйича тестлар, видео дарслар ва имтиҳон режими — ҳаммаси бир жойда.",
    home_start_tickets: "Билетларни бошлаш", home_start_exam: "Имтиҳон режими",
    home_free_start: "Бепул бошлаш", home_view_topics: "Мавзуларни кўриш",
    home_sections: "Барча ўқув бўлимлари", home_choose: "Ўзингизга қулай усулни танланг",
    home_begin: "Бошлаш →",
    home_cta_t: "Ҳозироқ бошланг",
    home_cta_s: "Бепул рўйхатдан ўтинг ва барча материалларга киринг",
    home_cta_btn: "Рўйхатдан ўтиш",
    home_welcome: "Салом,", home_continue: "қаердан давом этасиз?",
    stat_qs: "Саволлар", stat_tickets_l: "Билетлар", stat_topics_l: "Мавзулар", stat_videos_l: "Видео дарслар",
    feat_topics_t: "Мавзулар бўйича тест", feat_topics_d: "Ҳар бир мавзуни алоҳида ўрганинг. 30+ мавзу ва 1220 та савол.",
    feat_tickets_t: "Билетлар", feat_tickets_d: "Расмий имтиҳон билетлари — 61 та билет, ҳар бирида 20 та савол.",
    feat_exam_t: "Имтиҳон режими", feat_exam_d: "Тасодифий 50 ёки 100 та савол. Вақт чегараси билан ўзингизни синанг.",
    feat_videos_t: "Видео дарслар", feat_videos_d: "Ҳайдовчилик қоидаларини видео орқали ўрганинг. Модуллар бўйича.",
    feat_battle_t: "1vs1 Рақобат", feat_battle_d: "Дўстингиз ёки тасодифий рақиб билан беллашинг. Ким тезроқ ва тўғрироқ?",
    feat_marathon_t: "Марафон режими", feat_marathon_d: "Ҳар бир тўғри жавоб учун +1 савол. Имкон қадар узоқроқ чидан!",
    feat_hard_t: "Мураккаб саволлар", feat_hard_d: "Энг қийин саволлар тўплами. Тайёргарлигингизни синаб кўринг.",
    feat_num_t: "Рақамли саволлар", feat_num_d: "Рақамлар ва меъёрлар бўйича махсус саволлар.",
    feat_50_t: "50 та савол", feat_50_d: "Тезкор машқ — 50 та тасодифий савол, 50 дақиқа вақт.",
    feat_100_t: "100 та савол", feat_100_d: "Кенг қамровли машқ — 100 та тасодифий савол, 100 дақиқа вақт.",
    // Imtihon simulation
    sim_title: "Имтиҳон симуляцияси", sim_sub: "20 та савол · 3 хато = йиқилиш · 20 дақиқа",
    sim_rules_t: "Имтиҳон қоидалари",
    sim_rule1: "20 та тасодифий савол берилади",
    sim_rule2: "3 та хато қилсангиз имтиҳон дарҳол тугайди",
    sim_rule3: "20 дақиқа вақт берилади",
    sim_rule4: "17 та тўғри жавоб (85%) — ўтиш чегараси",
    sim_errors: "Хатолар", sim_start: "Имтиҳонни бошлаш",
    sim_fail_t: "Имтиҳондан йиқилдингиз!", sim_fail_s: "3 та хато қилдингиз.",
    sim_time_up: "Вақт тугади!", sim_pass_t: "Табриклаймиз, ўтдингиз!",
    sim_pass_s: "Имтиҳондан муваффақиятли ўтдингиз.",
    sim_not_pass: "Ўта олмадингиз", sim_errors_made: "та хато",
    // Mashq
    mashq_title: "Машқ режими",
    // Xatolar
    xato_title: "Хатолар", xato_sub: "Охирги 20 та хато қилган саволлар",
    feat_xato_t: "Хатолар бўлими", feat_xato_d: "Охирги 20 та хато қилган саволларингиз билан машқ қилинг.",
    xato_empty: "Ҳали хато қилмагансиз!", xato_empty_sub: "Мавзулар ёки имтиҳон ишланг — хатолар бу ерда пайдо бўлади.",
    q_count: "та савол",
  },
};
